classDiagram

    SpaceObject <|-- FixedObject
    SpaceObject <|-- FreeObject
    Simulation "1" -- "*" SpaceObject : contains

    SpaceObject *-- SimpleVector : composition
    Simulation o-- SpaceObject : aggregation
    
    class Simulation {
        - current_tick: uint46_t = 0
        - last_tick: uint46_t
        - objects: vector<SpaceObject*>
        + addObject(SpaceObject&: object) void
        + removeObject(SpaceObject&: object) void
        + calculateSystem() void
        + checkCollisions() CollisionReport
        + nextStep() void
    }

    class SpaceObject {
        <<abstract>>
        # id: int ~readOnly, unique~
        # position: SimpleVector
        # mass: double
        # appliedForce: SimpleVector
        + calculateAppliedForce(const SpaceObject&: object) ~isAbstract~
        + recalculatePos(dt) ~isAbstract~
        + getPosition() SimpleVector
        + getAppliedForce() SimpleVector 
        + getMass() double
        + getId() int
    }

    class FixedObject {
        
    }

    class FreeObject {
        # acceleration: SimpleVector
        # velocity: SimpleVector
        + recalculateVelocity() SimpleVector
    }

    class SimpleVector {
        - x: double
        - y: double
        + getX() double
        + getY() double
        + setX(x: double) *SimpleVector
        + setY(y: double) *SimpleVector
        + abs() double
        + operator+(vec&: SimpleVector) SimpleVector
        + operator+=(vec&: SimpleVector) void
        + operator-(vec&: SimpleVector) SimpleVector
        + operator-=(vec&: SimpleVector) void
        + operator*(double scalar) SimpleVector
        + operator*=(double scalar) void
        + $getUnitVector() SimpleVector
        + operator<<(double scalar) void
    }

    class CollisionReport {
        - object_1: SpaceObject*
        - object_2: SpaceObject*
        - coordinates: SimpleVector
        + getObject1() SpaceObject
        + getObject2() SpaceObject
        + getCoordinates() SimpleVector
        + printReport() void
    }

    class Physics {
        <<namespace>>
        + GRAVITATIONAL_CONSTANT double
        + calculateGravitationalForce(m1, m2, dist) double
    }

    class console {
        <<namespace>>
        + outputObjectInfo() void
    }

    class logger {
        <<namespace>>
    }