classDiagram

    %% Inheritance
    SpaceObject <|-- FixedObject
    SpaceObject <|-- FreeObject

    %% Structural Relationships
    Simulation o-- SpaceObject : manages (aggregation)
    SpaceObject *-- SimpleVector : has position/force (composition)
    CollisionReport *-- SimpleVector : collision point (composition)

    %% Dependencies (Usage)
    Simulation ..> CollisionReport : creates
    FreeObject ..> Physics : uses for gravity
    logs ..> SpaceObject : logs data
    csvLog ..> logs : provides stream
    
    class Simulation {
        - current_tick: uint64_t = 0
        - last_tick: uint64_t
        - objects: vector<SpaceObject*>
        + addObject(SpaceObject&: object) void
        + removeObject(SpaceObject&: object) void
        + calculateSystem() void
        + checkCollisions() CollisionReport <<not implemented>>
        + nextStep() void
    }

    class SpaceObject {
        <<abstract>>
        # id: int ~readOnly, unique~
        # position: SimpleVector
        # mass: double
        # appliedForce: SimpleVector
        + calculateAppliedForce(const SpaceObject&: object) ~isAbstract~
        + recalculatePos(dt: double) ~isAbstract~
        + getPosition() SimpleVector
        + getAppliedForce() SimpleVector 
        + getMass() double
        + getId() int
    }

    class FixedObject {
        
    }

    class FreeObject {
        # acceleration: SimpleVector
        # velocity: SimpleVector
        + recalculateVelocity(dt: double) SimpleVector
    }

    class SimpleVector {
        - x: double
        - y: double
        + getX() double
        + getY() double
        + setX(x: double) *SimpleVector
        + setY(y: double) *SimpleVector
        + abs() double
        + operator+(vec&: SimpleVector) SimpleVector
        + operator+=(vec&: SimpleVector) void
        + operator-(vec&: SimpleVector) SimpleVector
        + operator-=(vec&: SimpleVector) void
        + operator*(double: scalar) SimpleVector
        + operator*=(double: scalar) void
        + getUnitVector() SimpleVector
        + operator<<(double scalar) void
    }

    class CollisionReport {
        <<perspective>>
        - object_1: SpaceObject*
        - object_2: SpaceObject*
        - coordinates: SimpleVector
        + getObject1() SpaceObject
        + getObject2() SpaceObject
        + getCoordinates() SimpleVector
        + printReport() void
    }

    class Physics {
        <<namespace>>
        + GRAVITATIONAL_CONSTANT double
        + calculateGravitationalForce(m1: double, m2: double, dist: double) double
    }

    class logs {
        <<namespace>>
        startLogTable(stream: ostream&) void
        logFullObjectInfo(stream: ostream&, obj: SpaceObject*, tick: int)
    }

    class csvLog {
        <<namespace>>
        + $DEFAULT_FILE_NAME: string = "simulation_result.csv"
        + startLog(): fstream
        + closeLog(myFile: fstream&)
    }