flowchart TD
    %% Nodes
        A(Start)
        B[[Create Simulation-Object]]
        C[[Create and add SpaceObject's]]
        IF1{Simulation running}
        IF1_A[For all SpaceObject's: calculateAppliedForce other objects]
        IF1_B[[For all SpaceObject's: recalculatePosition]]
        IF1_B1[[Collision processing]]
        IF1_C[[Graphics update, logging, etc.]]
        D(End)
    %% Connections
        A --> B --> C --> IF1 --> IF1_A --> IF1_B --> IF1_B1 --> IF1_C --> IF1 --> D