flowchart TD
    %% Nodes
    Start(Start)
    InitSim[[Create Simulation Object]]
    AddObj[[Create and add SpaceObjects]]
    
    %% Loop Condition
    LoopStart{Tick < Last Tick?}
    
    %% Simulation Logic
    CalcForce[For each SpaceObject:<br/>calculateAppliedForce]
    MoveObj[For each SpaceObject:<br/>recalculatePos]
    Collisions[[Collision processing]]
    Logging[[Log Object Info to CSV/Console]]
    Graphics[[Update graphics]]
    Visualisation[[Diagram visualisation]]
    
    End(End)

    %% Connections
    Start --> InitSim --> AddObj --> LoopStart
    
    LoopStart -- Yes --> CalcForce
    CalcForce --> MoveObj
    MoveObj --> Collisions
    Collisions --> Logging
    
    %% Return to loop
    Logging --> Graphics --> LoopStart
    
    LoopStart -- No --> Visualisation --> End

    %% Grouping to match Code Structure
    subgraph Simulation::calculateSystem
        CalcForce
        MoveObj
        Collisions
    end

    %% Styling
    style Collisions fill:#f9f9f9,stroke:#999,stroke-dasharray: 5 5
    classDef future color:#888
    class Collisions future

    style Graphics fill:#f9f9f9,stroke:#999,stroke-dasharray: 5 5
    class Graphicss future

    style Visualisation fill:#f9f9f9,stroke:#999,stroke-dasharray: 5 5
    class Visualisation future